// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7vxozlp2lSY8WD6LUk9JDerF_5WSVsYw',
    appId: '1:279055630253:web:54bf46c99f462996ea2b24',
    messagingSenderId: '279055630253',
    projectId: 'task-14733',
    authDomain: 'task-14733.firebaseapp.com',
    storageBucket: 'task-14733.firebasestorage.app',
    measurementId: 'G-D0XFK3Z2ZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQgacOpHXGS7-nLEN6Cn_EvBK1Rib7fKA',
    appId: '1:279055630253:android:35b87c7c0fffc446ea2b24',
    messagingSenderId: '279055630253',
    projectId: 'task-14733',
    storageBucket: 'task-14733.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIoO-4a544-HnG2LRf36CXNlKnK_vCqsg',
    appId: '1:279055630253:ios:d3abca32b1c4a680ea2b24',
    messagingSenderId: '279055630253',
    projectId: 'task-14733',
    storageBucket: 'task-14733.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIoO-4a544-HnG2LRf36CXNlKnK_vCqsg',
    appId: '1:279055630253:ios:d3abca32b1c4a680ea2b24',
    messagingSenderId: '279055630253',
    projectId: 'task-14733',
    storageBucket: 'task-14733.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7vxozlp2lSY8WD6LUk9JDerF_5WSVsYw',
    appId: '1:279055630253:web:683e894ffe4d3c1bea2b24',
    messagingSenderId: '279055630253',
    projectId: 'task-14733',
    authDomain: 'task-14733.firebaseapp.com',
    storageBucket: 'task-14733.firebasestorage.app',
    measurementId: 'G-S863BCDKN4',
  );
}
