// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0xj0_sAi1X8Cj7M3uOM4DP-AP1zQcHl0',
    appId: '1:1051110844459:web:b14c627e7af6c28b2f226e',
    messagingSenderId: '1051110844459',
    projectId: 'task-manager-ee8d6',
    authDomain: 'task-manager-ee8d6.firebaseapp.com',
    storageBucket: 'task-manager-ee8d6.firebasestorage.app',
    measurementId: 'G-JN3PGQ86F1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd3yxpw5jef3l0Ptw83nfVuYchEpNfzmQ',
    appId: '1:1051110844459:android:b722f0543a20a8eb2f226e',
    messagingSenderId: '1051110844459',
    projectId: 'task-manager-ee8d6',
    storageBucket: 'task-manager-ee8d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuns4lvjv1QNnlyZQqYbMuMSxjOR3yoaA',
    appId: '1:1051110844459:ios:6c07eeb67de4c1ae2f226e',
    messagingSenderId: '1051110844459',
    projectId: 'task-manager-ee8d6',
    storageBucket: 'task-manager-ee8d6.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuns4lvjv1QNnlyZQqYbMuMSxjOR3yoaA',
    appId: '1:1051110844459:ios:6c07eeb67de4c1ae2f226e',
    messagingSenderId: '1051110844459',
    projectId: 'task-manager-ee8d6',
    storageBucket: 'task-manager-ee8d6.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0xj0_sAi1X8Cj7M3uOM4DP-AP1zQcHl0',
    appId: '1:1051110844459:web:5067d8a98bf412052f226e',
    messagingSenderId: '1051110844459',
    projectId: 'task-manager-ee8d6',
    authDomain: 'task-manager-ee8d6.firebaseapp.com',
    storageBucket: 'task-manager-ee8d6.firebasestorage.app',
    measurementId: 'G-T34WNZDSL7',
  );
}
